### ISSUE TITLE
Non va piu

### ISSUE THREAD

**Issue by tsdx** [NeverWise/plugin.video.lacosa#2]
appiccico un log. Spero che tu riesca a trovare tempo per sistemarlo:

`21:48:56 T:139669987653376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/USER/.kodi/addons/plugin.video.lacosa/default.py", line 93, in <module>
                                                lc = LaCosa()
                                              File "/home/USER/.kodi/addons/plugin.video.lacosa/default.py", line 84, in __init__
                                                Util.playStream(self._handle, title, img, streams[1], 'video', { 'title' : title, 'plot' : descr })
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
21:48:56 T:139671345616960   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.lacosa/?id=v&page=http%3A%2F%2Fwww.la-cosa.it%2F2016%2F05%2F24%2Ftutti-i-danni-causati-dallolio-di-palma%2F]`

**Comment by NeverWise** [comment]
Fixed in the next version.

**Comment by tsdx** [comment]
thank you :)


Il 30/10/2016 17:04, NeverWise ha scritto:
> Fixed in the next version.
>
